### PR TITLE
Create HeroicHitesh_SS

### PR DESCRIPTION
**Pull request by HeroicHitesh**
## Issue that this pull request solves

Closes: # 145

## Proposed changes

Adding ss regarding #145 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe): 
While installing whatsapp-play on MAC-OS, there was an error
`ModuleNotFoundError: No module named 'colorama'`

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

Screenshot 2020-05-22 at 9 45 26 AM

Screenshot 2020-05-22 at 9 51 19 AM

## Other information

Is it required to install `colorama` manually or can we add it in the requirements.txt

### CODE REVIEW

**Comment by HeroicHitesh** [comment]
@rpotter12 @xandao6 Please have a look at it.

**Comment by HeroicHitesh** [comment]
I was successfully able to install whatsapp-play after installing `colorama`
So, do we need `colorama` in `requirements.txt`?

Screenshot 2020-05-22 at 10 09 31 AM

**Comment by HeroicHitesh** [comment]
Screenshot 2020-05-22 at 10 19 06 AM

Successfully executed tracking command

**Comment by priyansh19** [comment]
For successful completion of the issue #145 you must upload the screenshot of installation + Tracking info of any user 

And for that colorama, I think it needs to be added in requirements file .. raise an issue and we will add it in upcoming releases

**Comment by HeroicHitesh** [comment]
> I was successfully able to install whatsapp-play after installing `colorama`
> So, do we need `colorama` in `requirements.txt`?
> 
> Screenshot 2020-05-22 at 10 09 31 AM



> Screenshot 2020-05-22 at 10 19 06 AM
> 
> Successfully executed tracking command

@priyansh19 Added both screenshots

**Comment by HeroicHitesh** [comment]
> And for that colorama, I think it needs to be added in requirements file .. raise an issue and we will add it in upcoming releases

@priyansh19 created issue #354

**Comment by priyansh19** [comment]
@rpotter12 please review and merge this pr 😉

**Pull request merged**
