### PR TITLE
update in contributing.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #411 
Added 
1. How to add a remote(upstream) to an existing repo
2. Synchronize your fork

### CODE REVIEW

**Review by rpotter12 — CHANGES_REQUESTED** [review]
Thank you @khareyash05. LGTM :)

Please change the merge branch to develop. Your PR should be raise to develop branch. 

`rpotter12:develop` from `khareyash05:fix#411`

**Comment by khareyash05** [comment]
@rpotter12 Changed the base branch

**Comment by khareyash05** [comment]
Do I have to add something else as well? @rpotter12

**Review by rpotter12 — CHANGES_REQUESTED** [review]
@khareyash05, Update your branch with develop branch. Your branch is not even with develop branch.

**Comment by khareyash05** [comment]
I will do that

**Comment by khareyash05** [comment]
@rpotter12 Please check if the changes are done
Or else I shall create another pull request for the same

**Review by rpotter12 — CHANGES_REQUESTED** [review]
@khareyash05 your PR should have only your changes. ISSUE_TEMPLATE is not change by you. This should not be in your PR. Update your PR with upstream develop branch.

**Comment by khareyash05** [comment]
@rpotter12 I am closing this PR and creating a new PR .. I am not able to do what you want
give me few minutes

**Pull request closed without merging**
