### PR TITLE
I have successfully installed and executed the tracking commands you can checks from the screenshots attached

### PR DESCRIPTION
**Pull request by viduu**
Screenshot (3)
Screenshot (2)

### CODE REVIEW

**Comment by xandao6** [comment]
Your fork is outdated, please do a rebase first.

**Comment by suubh** [comment]
Screenshot from 2020-03-01 20-37-11

**Comment by xandao6** [comment]
@suubh  open you own PR.

**Comment by xandao6** [comment]
@viduu  You haven't executed the tracking command.

**Comment by suubh** [comment]
I did sir

**Comment by viduu** [comment]
@xandao6 ok you can check it again sir
Screenshot (4)

**Pull request closed without merging**
