### PR TITLE
File Sharing feature added(Isuue #244)

### PR DESCRIPTION
**Pull request by zulkernine**
Through this pull request I added the feature of Sharing file through wchat .
Issue #244 
Files are sent by the File-Attach option of whats-app-web. Type '#_FILE" in the message section in CLI and press enter, this will open a file dialogue box(OS provided), select the files(Image, Video, Documents etc.) and send it.
Screenshots are attached demonstrating this. :)

Screenshot from 2020-03-23 22-03-29
WhatsApp Image 2020-03-23 at 9 37 36 PM

Dialogue box to choose files is shown below. This is OS dependent(Mine is Kali). 
Screenshot from 2020-03-23 22-54-55

### CODE REVIEW

**Comment by rpotter12** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- wplay/utils/io.py  1
- wplay/wchat.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/rpotter12/whatsapp-play/pullRequest?prid=5229956&bid=17145510)

**Comment by rpotter12** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- wplay/utils/io.py  1
- wplay/wchat.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/rpotter12/whatsapp-play/pullRequest?prid=5229956&bid=17145510)

**Comment by zulkernine** [comment]
Ok 😃

**Comment by xandao6** [comment]
Look's good, tomorrow I will see carefully the commits.

**Pull request merged**
