### PR TITLE
Issue #145

### PR DESCRIPTION
**Pull request by csharp489**
Here I am enclosing the screenshort of successfully execution of tracking command .
Screenshot (152)

### CODE REVIEW

**Comment by rpotter12** [comment]
@csharp489 update your fork with upstream. Your fork is some commits behind.

**Comment by xandao6** [comment]
You need to push the screenshot also.

**Comment by danilofuchs** [comment]
> @csharp489 update your fork with upstream. Your fork is some commits behind.

You can follow the same advice: https://github.com/rpotter12/whatsapp-play/pull/151#issuecomment-593168694

**Comment by rpotter12** [comment]
@csharp489 add the execution screenshot in the screenshot folder, commit them and open a PR for that. 
This is the task of #145

**Comment by csharp489** [comment]
Please refer #168 in pull request for complete PR.
Hope you find this .

**Pull request closed without merging**
