### PR TITLE
Uploading-screenshots

### PR DESCRIPTION
**Pull request by vaquersame**
## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by vaquersame** [comment]
Captura
Captura_2

**Comment by priyansh19** [comment]
@vaquersame Read issue #145 and then make a PR
You haven't added these screenshots in the screenshots folder of upstream while making a PR 
and also add a screenshot of tracking info of a person

**Comment by vaquersame** [comment]
Sorry I'm a novice, but as soon as I have time I can fix it.

**Comment by rpotter12** [comment]
@vaquersame Please read the task/issue carefully :)

**Comment by HeroicHitesh** [comment]
@vaquersame are you working on this issue? @rpotter12 is this issue still up-for-grabs?

**Comment by rpotter12** [comment]
@HeroicHitesh Read #145 issue. All the info is written in it:)

**Pull request closed without merging**
