### PR TITLE
Create kichloo_SS

### PR DESCRIPTION
**Pull request by kichloo**
## Issue that this pull request solves

Closes: #145 

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by kichloo** [comment]
**Screenshot 1**
kichloo_1

**Screenshot 2**
kichloo_2

**Screenshot 3**

kichloo_3

**Screenshot 4**
kichloo_4

**Comment by kichloo** [comment]
@rpotter12 @priyansh19 Done the required changes.

**Comment by priyansh19** [comment]
@kichloo You haven't added a screenshot of tracking status
and also add these screenshots in the screenshots folder

**Comment by kichloo** [comment]
@priyansh19 Can you please tell which command are you referring to?

**Comment by rpotter12** [comment]
@kichloo use `wplat -wt <target_name>`

**Comment by priyansh19** [comment]
And also add the installation and tracking screenshot in the folder of upstream

**Comment by HeroicHitesh** [comment]
@kichloo Are you working on the issue? @rpotter12 I will be installing the application now for contribution purposes so, I can help with installation and other screenshots if nobody is working on it.

**Pull request closed without merging**
