### PR TITLE
issue #147

### PR DESCRIPTION
**Pull request by anmolkaur18**
Uploaded the screenshots of Software working

### CODE REVIEW

**Comment by priyansh19** [comment]
Hi @anmolkaur18,
Rename your Screenshots with GitHub username
and also do mention those all Screenshots in this PR also

**Comment by anmolkaur18** [comment]
I did a rebase and then changed the name of screenshots with my username like anmolkaur18_screenshot1

**Comment by rpotter12** [comment]
@anmolkaur18 As you are deleting others screenshot, update your fork forcefully by upstream and create a new fresh PR. :)

**Comment by priyansh19** [comment]
@anmolkaur18 your fork is still not updated .. Your PR is still deleting other's screenshots

**Pull request closed without merging**
