### PR TITLE
whatsapp-play issue #145

### PR DESCRIPTION
**Pull request by Neelaksh-Singh**
[Beginners.docx](https://github.com/rpotter12/whatsapp-play/files/4274187/Beginners.docx)
These are the screenshots for successful installation of wplay.
Also one can see the tracker feature in action.

### CODE REVIEW

**Comment by priyansh19** [comment]
@Neelaksh-Singh Please make a few changes to your PR:
- Upload the Screenshots of installation in the Screenshots folder of your forked repository.
- Update your Pull request and add Screenshots here in the comment section also.

**Comment by Neelaksh-Singh** [comment]
@xandao6 ,@priyansh19 i was thinkinf of adding text to speech in our software.
Can i please take it up as a part of our gssoc 20

**Comment by rpotter12** [comment]
@Neelaksh-Singh In third screenshot, the process was killed. You were not able to track the target. Please try again and upload screenshot of that :)

**Comment by rpotter12** [comment]
> @xandao6 ,@priyansh19 i was thinkinf of adding text to speech in our software.
> Can i please take it up as a part of our gssoc 20

@Neelaksh-Singh can you please elaborate, why this can be added??

**Comment by Neelaksh-Singh** [comment]
i was met with an installation error .

image

**Comment by Neelaksh-Singh** [comment]
can u guide me what to do next

**Comment by Neelaksh-Singh** [comment]
> > @xandao6 ,@priyansh19 i was thinkinf of adding text to speech in our software.
> > Can i please take it up as a part of our gssoc 20
> 
> @Neelaksh-Singh can you please elaborate, why this can be added??

Since whatsapp has voice message option , and also since we are using cli for bombing a certain message , we can also bombard a list of people with voice messages

**Comment by rpotter12** [comment]
> can u guide me what to do next

try `pip install wplay` again.

> Since whatsapp has voice message option , and also since we are using cli for bombing a certain > message , we can also bombard a list of people with voice messages

bombarding of a voice message is a good idea. Please open a issue for this :)

**Pull request closed without merging**
