### PR TITLE
add option to exit out of online_check

### PR DESCRIPTION
**Pull request by nileshpatra**
Solves #19

### CODE REVIEW

**Comment by nileshpatra** [comment]
@rpotter12 , we don't need the second while loop. The changes I made basically track the status of the user, and asks user after one minute if they are still interested to know the status of user. What we can do is to increase the time gap after which it asks user.
Pressing 'q' to stop the script is almost same as pressing 'ctrl+c' to stop the script. Where is the difference?

**Comment by rpotter12** [comment]
@nileshpatra the idea of the script was to track until the user stops the scripts. So there should not be any time limit for tracking.

**Comment by nileshpatra** [comment]
@rpotter12 if that is the case then the initial code goes well with it - pressing q or ctrl+C, it doesn't make a big difference. If we have to add an option for exit , then we need to change the script for tracking for a finite duration.

**Comment by rpotter12** [comment]
@nileshpatra According to the idea the script should not run for a particular duration.

**Pull request closed without merging**
