### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by kichloo**
The PR consists of the SS of the installation of whatsapp-play.

### CODE REVIEW

**Comment by kichloo** [comment]
Fixes #145

**Comment by kichloo** [comment]
@rpotter12 In the SS folder, it says that the files cannot be uploaded. Pl do something regarding it.

**Comment by priyansh19** [comment]
> @rpotter12 In the SS folder, it says that the files cannot be uploaded. Pl do something regarding it.

Discuss the error you are getting in the slack channel

**Comment by kichloo** [comment]
@rpotter12 I know got to know how to do it, so I am closing this PR and opening another one with the changes as you said.

**Pull request closed without merging**
