### PR TITLE
Installed the software and ran the tracking commands

### PR DESCRIPTION
**Pull request by pratyushraj7**
## Issue that this pull request solves

Closes: 

## Proposed changes

Installed the software and ran the tracking commands successfully. The screenshots are attached below.

## Types of changes

_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [] Documentation update (Documentation content changed)
- [x] Other (please describe):  Installed the software and ran the tracking commands successfully

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

The screenshots are attached below.

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by rpotter12** [comment]
@pratyushraj7 add your screenshots in comments also so that we can review them

**Comment by pratyushraj7** [comment]
Screenshot (61)
Screenshot (62)


DONE!

**Comment by rpotter12** [comment]
@pratyushraj7 your images are not visible. Please check it again

**Comment by pratyushraj7** [comment]
[
Screenshot (61)
Screenshot (62)

](url)

@rpotter12 , please check now!

**Pull request merged**
