### PR TITLE
Pyppeteer ready!

### PR DESCRIPTION
**Pull request by xandao6**
I've created **pyppeteerUtils.py** to be easy to modify all other scripts
I've created a **HOW TO USE** in **pyppeteerUtils.py** and added an **example**
I've implemented **pyppeteerUtils** in **messageblast.py**

I've modified **wplay.py** to accept pyppeteer for messageblast script, we need to put an **await** in the further scripts that we will change.

I worked hard, hope you enjoy!

### CODE REVIEW

**Comment by rpotter12** [comment]
@xandao6 Great work. This PR is having a lot of great work. It will take some time to checka and test all the scripts.

**Comment by rpotter12** [comment]
@xandao6 I have seen your active participation and quality of work in the project. Seeing your good quality of work I have sent you a collaborator invitation mail. 

I hope we will make this software a great project. :)
WELCOME TO THE PROJECT!!

**Comment by xandao6** [comment]
Thank you!

**Comment by xandao6** [comment]
> @xandao6 Great work. This PR is having a lot of great work. It will take some time to checka and test all the scripts.

Currently only messageblast was implemented with pyppeteer, I will send the commits of others soon.

**Pull request merged**
