### PR TITLE
Screenshot of installation

### PR DESCRIPTION
**Pull request by 97shivank**
## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by rpotter12** [comment]
@97shivank add your screenshots in comments also so that we can review them

**Comment by 97shivank** [comment]
i'm getting this error. can you review it.

**Comment by rpotter12** [comment]
show your error in comments :)

**Comment by priyansh19** [comment]
@97shivank if you have any issue then we can discuss it on slack

**Comment by rpotter12** [comment]
> @97shivank add your screenshots in comments also so that we can review them

.

**Comment by 97shivank** [comment]
> > @97shivank add your screenshots in comments also so that we can review them
> 
> .

i've already added kindly look it.

**Comment by rpotter12** [comment]
@97shivank you have added screenshots in screetshot folder and commit them. Add those screenshot in PR's comment also :)

**Comment by 97shivank** [comment]
shivank_install
shivank_tracking
added..

**Comment by 97shivank** [comment]
I've installed it.kindly look at below screenshots @rpotter12

**Comment by 97shivank** [comment]
screen1
screen21

**Pull request merged**
