### PR TITLE
#145 issue resolved .Added screenshots and executed tracking command successfully

### PR DESCRIPTION
**Pull request by sim12cool**
## Issue that this pull request solves

Closes: # (issue number)
[https://docs.google.com/document/d/1hMkjEIWWL82P-dqZItmfIurSKFxXx2femCJazBasxAI/edit?usp=sharing](url)
## Proposed changes

Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

wapp installed and runned

tracking command

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by xandao6** [comment]
You can talk to me in slack for help if you want.

**Comment by priyansh19** [comment]
@sim12cool Rebase your current repository and then make a PR. 
We can discuss this over slack ..

**Comment by rpotter12** [comment]
@sim12cool you have not updated your fork properly. Please update your fork forcefully and make a fresh PR for it

**Comment by rpotter12** [comment]
@sim12cool create a new fresh PR for this :)

**Pull request closed without merging**
