### PR TITLE
UPDATE CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by khareyash05**
With reference to issue #411 
Updated contributing.md

### CODE REVIEW

**Comment by khareyash05** [comment]
@rpotter12 I have removed the file from my branch

**Review by rpotter12 — APPROVED** [review]
Thank you....LGTM

**Comment by khareyash05** [comment]
Thank You!
Could you please add a level label to the same as under the GSSOC guidelines?

**Comment by khareyash05** [comment]
hi @rpotter12  Could you pls add a level label and a GSSOC label to the PR as well because adding a level label to the PR is only being counted
Thanx!

**Pull request merged**
